/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.chess.engine;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest
{
    @Test void appExists()
    {
        App app = new App();
        assertNotEquals(app, null);
    }
}